#!/bin/bash
git pull
rm -rf vim/bundle/vundle
git clone https://github.com/gmarik/vundle vim/bundle/vundle
vim +BundleInstall +qall
cd ../
FILES=`ls dotfiles/ | grep -v install`
for f in $FILES
do
  echo .$f
  rm -rf ./.$f
  ln -s ./dotfiles/$f ./.$f
done
source ~/.bashrc
