syn keyword cType   u8 u16 u32 u64 i8 i16 i32 i64 f32 f64
syn keyword JPDebug ANEG APOS AZERO ANOTZERO ANULL ANOTNULL IGNORE ASSERT assert ASSERT_NO_ERROR ASSERT_DEBUG DEBUG
syn keyword JPTodo XXXANEG XXXAPOS XXXAZERO XXXANOTZERO XXXANULL XXXANOTNULL XXXIGNORE XXXASSERT TODO UNEXPECTED
