#!/bin/bash
set -euo pipefail

EXPECTED_NONTRACKED_FILES="^(.|`cat .gitignore | grep '^[^/]*/$' | tr -d '/' | tr '\n' '|'`)$"
NON_DOTFILES='^(util|README.md)$'

comm -3 --output-delimiter="++ " \
  <(ls -d ~/.* | sed -e 's/.*\/\.//' | grep -Ev $EXPECTED_NONTRACKED_FILES) \
  <(ls -d * | grep -Ev $NON_DOTFILES)
