#!/bin/bash

# Main entry point.
# Can be symlinked, probably from somewhere in $PATH.
# Sets up necessary contextual environment variables for command scripts.

set -euo pipefail

CMD=$1

SCRIPT_DIR="$(cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR"/.. && pwd)"

SCRIPT_DIR=$SCRIPT_DIR \
REPO_DIR=$REPO_DIR \
  $SCRIPT_DIR/$CMD
