#!/bin/bash
set -euo pipefail

HOMEDIR_FILE=$HOME/.$1
IMPORTED_FILE=$REPO_DIR/$1

if [ ! -e $HOMEDIR_FILE ]; then
  echo $HOMEDIR_FILE does not exist!
  exit 1
fi

if [ -e $IMPORTED_FILE ]; then
  echo $IMPORTED_FILE already exists!
  exit 1
fi

cp -r $HOMEDIR_FILE $IMPORTED_FILE
rm -rf $HOMEDIR_FILE
ln -s $IMPORTED_FILE $HOMEDIR_FILE

echo Imported .$1
