#!/bin/bash

# re-evaluate this
# raco pkg install --deps search-auto pollen
# raco pkg install --deps search-auto git://github.com/j3parker/desolarized
# raco pollen render *.pp

NON_DOTFILES='^(util|README.md)$'

for f in `ls $REPO_DIR/ | grep -Ev $NON_DOTFILES`
do
  if [ ${f: -2} != ".p" ]; then
    echo .$f
    rm -rf $HOME/.$f
    ln -s $REPO_DIR/$f $HOME/.$f
  fi
done
source $HOME/.bashrc

# vundle + vim install
rm -rf $REPO_DIR/vim/bundle/vundle
git clone https://github.com/gmarik/vundle $REPO_DIR/vim/bundle/vundle
vim +BundleInstall +qall

# re-evaluate this
# vimproc stuff
# cd $HOME/.vim/bundle/vimproc.vim
# make -f make_unix.mak

# ultisnips extra install steps
mkdir -p $HOME/.vim/ftdetect/
ln -fs $HOME/.vim/bundle/ultisnips/ftdetect/* $HOME/.vim/ftdetect/
rm -rf $HOME/.vim/bundle/ultisnips/UltiSnips

$SCRIPT_DIR/cleanup
